=== sunsided/rubyrush/RubyLogic/PatternDefinitions.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ruby="urn:RubyRush:PatternDefinition:1.0" targetNamespace="urn:RubyRush:PatternDefinition:1.0">
  
  <!-- root element -->
  <xsd:element name="PatternDefinitions">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ruby:Pattern" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!-- pattern definition -->
  <xsd:element name="Pattern">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ruby:Match" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="rank" use="required" type="xsd:positiveInteger" />
      <xsd:attribute name="name" default="" type="xsd:string" />
      <xsd:attribute name="isSymmetric" default="false" type="xsd:boolean" />
    </xsd:complexType>  
  </xsd:element>

  <!-- pattern definition -->
  <xsd:element name="SubPattern">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ruby:Match" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!-- match definition -->
  <xsd:element name="Match">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ruby:SubPattern" minOccurs="0" maxOccurs="2" />
      </xsd:sequence>
      <xsd:attribute name="type" default="equality">
        <xsd:simpleType>
          <xsd:restriction base="xsd:NMTOKEN">
            <xsd:enumeration value="equality" />
            <xsd:enumeration value="inequality" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="candidateType" default="none">
        <xsd:simpleType>
          <xsd:restriction base="xsd:NMTOKEN">
            <xsd:enumeration value="none" />
            <xsd:enumeration value="backward" />
            <xsd:enumeration value="forward" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  
</xsd:schema>

=== sunsided/rubyrush/RubyLogic/PatternDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<PatternDefinitions xmlns="urn:RubyRush:PatternDefinition:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:RubyRush:PatternDefinition:1.0 PatternDefinitions.xsd">
  <Pattern rank="1" name="XXOX">
    <Match type="equality" />
    <Match type="equality" />
    <Match type="invariant"/>
    <Match type="equality" candidateType="backward" />
  </Pattern>

  <Pattern rank="1" name="XXO">
    <Match type="equality" />
    <Match type="equality" />
    <Match type="invariant">
      <SubPattern>
        <Match type="equality" candidateType="backward" />
      </SubPattern>
    </Match>
  </Pattern>

  <Pattern rank="1" name="XOX" isSymmetric="true">
    <Match type="equality" />
    <Match type="invariant">
      <SubPattern>
        <Match type="equality" candidateType="backward" />
      </SubPattern>
    </Match>
    <Match type="equality" />
  </Pattern>

  <Pattern rank="4" name="XXOX2">
    <Match type="equality" />
    <Match type="equality" />
    <Match type="invariant">
      <SubPattern>
        <Match type="equality" candidateType="backward" />
      </SubPattern>
    </Match>
    <Match type="equality" />
  </Pattern>

  <Pattern rank="7" name="XXOXX-Bomb">
    <Match type="equality" />
    <Match type="equality" />
    <Match type="invariant">
      <SubPattern>
        <Match type="equality" candidateType="backward" />
      </SubPattern>
    </Match>
    <Match type="equality" />
    <Match type="equality" />
  </Pattern>

  <Pattern rank="6" name="XXOX-Cross">
    <Match type="equality" />
    <Match type="equality" />
    <Match type="invariant">
      <SubPattern>
        <Match type="equality" />
        <Match type="equality" />
      </SubPattern>
    </Match>
    <Match type="equality" candidateType="backward" />
  </Pattern>

  <Pattern rank="100" name="XXOXX-Cross">
    <Match type="equality" />
    <Match type="equality" />
    <Match type="invariant">
      <SubPattern>
        <Match type="equality" />
        <Match type="equality" />
      </SubPattern>
      <SubPattern>
        <Match type="equality" />
        <Match type="equality" />
      </SubPattern>
    </Match>
    <Match type="equality" candidateType="backward" />
  </Pattern>
</PatternDefinitions>
